Repository AY2223S2-CS2103T-W13-3/tp, pull requests merged in 2023-03, with the labels that each got.

#50 Create Date class and testcases
  src/main/java/seedu/task/model/task/Date.java
  src/main/java/seedu/task/model/task/Description.java
  src/test/java/seedu/task/model/task/DateTest.java
Labels: type.Story, priority.High

#59 Add support for SimpleTask, Deadline and Event
  README.md
  docs/UserGuide.md
  docs/images/Ui_02.png
  src/main/java/seedu/task/logic/commands/EditCommand.java
  src/main/java/seedu/task/logic/parser/AddCommandParser.java
  src/main/java/seedu/task/logic/parser/CliSyntax.java
  src/main/java/seedu/task/logic/parser/ParserUtil.java
  src/main/java/seedu/task/model/task/Date.java
  src/main/java/seedu/task/model/task/Deadline.java
  src/main/java/seedu/task/model/task/Event.java
  src/main/java/seedu/task/model/task/SimpleTask.java
  src/main/java/seedu/task/model/task/Task.java
  src/main/java/seedu/task/model/util/SampleDataUtil.java
  src/main/java/seedu/task/storage/JsonAdaptedTask.java
  src/main/java/seedu/task/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/task/logic/LogicManagerTest.java
  src/test/java/seedu/task/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/task/logic/commands/AddCommandTest.java
  src/test/java/seedu/task/logic/commands/EditCommandTest.java
  src/test/java/seedu/task/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/task/logic/parser/ParserUtilTest.java
  src/test/java/seedu/task/logic/parser/TaskBookParserTest.java
  src/test/java/seedu/task/model/TaskBookTest.java
  src/test/java/seedu/task/model/task/DateTest.java
  src/test/java/seedu/task/model/task/DeadlineTest.java
  src/test/java/seedu/task/model/task/DescContainsKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/EventTest.java
  src/test/java/seedu/task/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/SimpleTaskTest.java
  src/test/java/seedu/task/model/task/TagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/UniqueTaskListTest.java
  src/test/java/seedu/task/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/task/testutil/DeadlineBuilder.java
  src/test/java/seedu/task/testutil/EventBuilder.java
  src/test/java/seedu/task/testutil/SimpleTaskBuilder.java
  src/test/java/seedu/task/testutil/TypicalDeadlines.java
  src/test/java/seedu/task/testutil/TypicalEvents.java
  src/test/java/seedu/task/testutil/TypicalTasks.java
Labels: priority.High

#63 Add basic stats feature
  docs/UserGuide.md
  docs/images/johndoe.png
  docs/images/programmerhao.png
  src/main/java/seedu/task/logic/commands/StatsCommand.java
  src/main/java/seedu/task/logic/parser/AddCommandParser.java
  src/main/java/seedu/task/logic/parser/TaskBookParser.java
  src/main/java/seedu/task/model/tracker/TagComparator.java
  src/main/java/seedu/task/model/tracker/TaskByTagTracker.java
  src/test/java/seedu/task/model/tracker/TagComparatorTest.java
  src/test/java/seedu/task/model/tracker/TaskByTagTrackerTest.java
  src/test/java/seedu/task/testutil/TagComparatorBuilder.java
  src/test/java/seedu/task/testutil/TypicalTagComparator.java
  src/test/java/seedu/task/testutil/TypicalTasks.java
Labels: type.Story, priority.High

#64 Update UserGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.High

#68 Edit helplink to clock-work's UG
  src/main/java/seedu/task/ui/HelpWindow.java
Labels: priority.High, type.Chore

#65 Enhanced find method
  docs/UserGuide.md
  src/main/java/seedu/task/logic/commands/ExitCommand.java
  src/main/java/seedu/task/logic/commands/FindCommand.java
  src/main/java/seedu/task/logic/parser/CliSyntax.java
  src/main/java/seedu/task/logic/parser/FindCommandParser.java
  src/main/java/seedu/task/logic/parser/ParserUtil.java
  src/main/java/seedu/task/model/Model.java
  src/main/java/seedu/task/model/ModelManager.java
  src/main/java/seedu/task/model/TaskBook.java
  src/main/java/seedu/task/model/tag/Tag.java
  src/main/java/seedu/task/model/task/Date.java
  src/main/java/seedu/task/model/task/DeadlineDateContainsKeywordsPredicate.java
  src/main/java/seedu/task/model/task/DescContainsAllKeywordsPredicate.java
  src/main/java/seedu/task/model/task/DescContainsKeywordsPredicate.java
  src/main/java/seedu/task/model/task/EventFromContainsKeywordsPredicate.java
  src/main/java/seedu/task/model/task/EventToContainsKeywordsPredicate.java
  src/main/java/seedu/task/model/task/NameContainsAllKeywordsPredicate.java
  src/main/java/seedu/task/model/task/TagsContainsAllKeywordsPredicate.java
  src/main/java/seedu/task/model/task/Task.java
  src/main/java/seedu/task/model/task/UniqueTaskList.java
  src/test/java/seedu/task/logic/commands/FindCommandTest.java
  src/test/java/seedu/task/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/task/logic/parser/TaskBookParserTest.java
  src/test/java/seedu/task/model/task/DescContainsAllKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/DescContainsKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/NameContainsAllKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/TagsContainsAllKeywordsPredicateTest.java
  src/test/java/seedu/task/model/task/TagsContainsKeywordsPredicateTest.java
Labels: priority.High

#72 Bug fixes
  src/main/java/seedu/task/logic/commands/AddCommand.java
  src/main/java/seedu/task/ui/HelpWindow.java
Labels: type.Chore, type.Bug, severity.Low

#74 Add color code
  README.md
  src/main/java/seedu/task/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Story

#75 Update TaskCard.java
  src/main/java/seedu/task/ui/TaskCard.java
Labels: priority.High, type.Bug, severity.High

#77 Edit Tag text color and remove navy background color
  src/main/java/seedu/task/ui/TaskCard.java
Labels: type.Chore

#78 Up coming alert feature
  docs/UserGuide.md
  src/main/java/seedu/task/commons/core/Messages.java
  src/main/java/seedu/task/logic/Logic.java
  src/main/java/seedu/task/logic/LogicManager.java
  src/main/java/seedu/task/logic/commands/AlertCommand.java
  src/main/java/seedu/task/logic/commands/CommandResult.java
  src/main/java/seedu/task/logic/parser/AlertCommandParser.java
  src/main/java/seedu/task/logic/parser/ParserUtil.java
  src/main/java/seedu/task/logic/parser/TaskBookParser.java
  src/main/java/seedu/task/model/Model.java
  src/main/java/seedu/task/model/ModelManager.java
  src/main/java/seedu/task/model/task/Deadline.java
  src/main/java/seedu/task/model/task/Event.java
  src/main/java/seedu/task/model/task/SimpleTask.java
  src/main/java/seedu/task/model/task/StartupTaskWithinTimelinePredicate.java
  src/main/java/seedu/task/model/task/Task.java
  src/main/java/seedu/task/model/task/TaskWithinTimelinePredicate.java
  src/main/java/seedu/task/storage/JsonAdaptedTask.java
  src/main/java/seedu/task/ui/AlertWindow.java
  src/main/java/seedu/task/ui/MainWindow.java
  src/main/resources/view/AlertWindow.fxml
  src/test/java/seedu/task/logic/commands/AddCommandTest.java
  src/test/java/seedu/task/logic/commands/AlertCommandTest.java
  src/test/java/seedu/task/logic/parser/AlertCommandParserTest.java
  src/test/java/seedu/task/logic/parser/ParserUtilTest.java
  src/test/java/seedu/task/model/task/DeadlineTest.java
  src/test/java/seedu/task/model/task/EventTest.java
  src/test/java/seedu/task/model/task/StartupTaskWithinTimelinePredicateTest.java
  src/test/java/seedu/task/model/task/TaskWithinTimelinePredicateTest.java
  src/test/java/seedu/task/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/task/testutil/DeadlineBuilder.java
  src/test/java/seedu/task/testutil/EventBuilder.java
  src/test/java/seedu/task/testutil/SimpleTaskBuilder.java
  src/test/java/seedu/task/testutil/TypicalComplicatedTasks.java
Labels: type.Story, priority.High

#89 Clean up UG
  docs/UserGuide.md
  docs/team/johndoe.md
Labels: type.documentation

#91 Update UserGuide.md
  docs/UserGuide.md
Labels: type.documentation

#94 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/SortCommandActivityDiagram.png
  docs/images/SortCommandSequenceDiagram.png
Labels: type.documentation, priority.High

#99 Update DG Find Command
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: type.documentation, priority.High

#114 Enable Assertions and Update Sort DG
  build.gradle
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/SortCommandSequenceDiagram.png
Labels: type.Chore

#116 Update UserGuide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.documentation

#113 Update DG Delete Command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandActivityDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteCommandActivityDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/index.md
  src/main/java/seedu/task/logic/commands/DeleteCommand.java
Labels: type.documentation, priority.High

#119 DG updates
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddCommand.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddCommand.png
  docs/images/programmerhao.jpg
  docs/images/programmerhao.png
Labels: type.documentation, priority.High

#118 Make description optional
  src/main/java/seedu/task/logic/parser/AddCommandParser.java
  src/main/java/seedu/task/logic/parser/EditCommandParser.java
  src/main/java/seedu/task/logic/parser/ParserUtil.java
  src/main/java/seedu/task/model/task/DescContainsKeywordsPredicate.java
  src/main/java/seedu/task/model/task/Description.java
  src/main/java/seedu/task/model/task/Task.java
  src/main/java/seedu/task/model/util/SampleDataUtil.java
  src/main/java/seedu/task/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableTaskBookTest/duplicateTaskTaskBook.json
  src/test/data/JsonSerializableTaskBookTest/typicalTasksTaskBook.json
  src/test/java/seedu/task/logic/commands/CommandTestUtil.java
  src/test/java/seedu/task/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/task/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/task/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/task/testutil/SimpleTaskBuilder.java
  src/test/java/seedu/task/testutil/TypicalTasks.java
Labels: priority.High, type.Bug, severity.Medium

#137 Alert and Find bug fixes
  src/main/java/seedu/task/logic/parser/AddCommandParser.java
  src/main/java/seedu/task/logic/parser/AlertCommandParser.java
  src/main/java/seedu/task/ui/AlertWindow.java
  src/main/java/seedu/task/ui/MainWindow.java
  src/test/java/seedu/task/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/task/logic/parser/AlertCommandParserTest.java
Labels: type.Bug

#135 Sub task
  docs/UserGuide.md
  src/main/java/seedu/task/Main.java
  src/main/java/seedu/task/logic/commands/AddSubtaskCommand.java
  src/main/java/seedu/task/logic/commands/DeleteSubtaskCommand.java
  src/main/java/seedu/task/logic/commands/EditCommand.java
  src/main/java/seedu/task/logic/parser/AddSubtaskParser.java
  src/main/java/seedu/task/logic/parser/CliSyntax.java
  src/main/java/seedu/task/logic/parser/DeleteSubtaskParser.java
  src/main/java/seedu/task/logic/parser/ParserUtil.java
  src/main/java/seedu/task/logic/parser/TaskBookParser.java
  src/main/java/seedu/task/model/task/Deadline.java
  src/main/java/seedu/task/model/task/Description.java
  src/main/java/seedu/task/model/task/Event.java
  src/main/java/seedu/task/model/task/Name.java
  src/main/java/seedu/task/model/task/SimpleTask.java
  src/main/java/seedu/task/model/task/Subtask.java
  src/main/java/seedu/task/model/task/Task.java
  src/main/java/seedu/task/model/task/UniqueSubtaskList.java
  src/main/java/seedu/task/storage/JsonAdaptedSubtask.java
  src/main/java/seedu/task/storage/JsonAdaptedTask.java
  src/main/java/seedu/task/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/task/logic/commands/AddSubtaskCommandTest.java
  src/test/java/seedu/task/logic/commands/CommandTestUtil.java
  src/test/java/seedu/task/logic/commands/DeleteSubtaskCommandTest.java
  src/test/java/seedu/task/logic/parser/AddSubtaskParserTest.java
  src/test/java/seedu/task/logic/parser/DeleteSubtaskParserTest.java
  src/test/java/seedu/task/model/task/SubtaskTest.java
  src/test/java/seedu/task/storage/JsonAdaptedSubtaskTest.java
  src/test/java/seedu/task/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/task/testutil/SimpleTaskBuilder.java
  src/test/java/seedu/task/testutil/SubtaskBuilder.java
  src/test/java/seedu/task/testutil/TypicalSubtasks.java
  src/test/java/seedu/task/testutil/TypicalTasks.java
Labels: priority.High

#142 V1.3 dg
  docs/UserGuide.md
Labels: type.documentation

#149 Edited pictures to display Task instead of Address + remove unused images
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommand.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/RemoveSubsectionSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/SubsectionSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/AddCommand.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/RemoveSubsectionSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/SubsectionSequenceDiagram.png
  docs/images/Ui_02.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/request_access.png
  src/main/java/seedu/task/ui/HelpWindow.java
Labels: type.documentation, type.Chore

#152 Bug fix edit command
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/task/logic/commands/EditCommand.java
  src/main/java/seedu/task/logic/parser/EditCommandParser.java
  src/main/java/seedu/task/logic/parser/FindCommandParser.java
  src/test/java/seedu/task/logic/commands/CommandTestUtil.java
  src/test/java/seedu/task/logic/commands/EditCommandTest.java
  src/test/java/seedu/task/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/task/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/task/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/task/testutil/TypicalTasks.java
Labels: priority.High, type.Bug, severity.High
