Repository AY2223S2-CS2103T-W13-3/tp, pull requests merged in 2023-04, with the labels that each got.

#194 Update @Huggenguggen PPP and UG
  docs/UserGuide.md
  docs/images/alertDoc.png
  docs/images/findDoc.png
  docs/images/usecaseAdd.png
  docs/team/huggenguggen.md
Labels: type.documentation

#197 lywich PPP + fix links in UG + typo fix
  docs/UserGuide.md
  docs/team/huggenguggen.md
  docs/team/lywich.md
Labels: type.documentation

#199 Update DG and @Huggenguggen PPP
  docs/DeveloperGuide.md
  docs/images/text-wrap0.png
  docs/images/text-wrap1.png
  docs/images/text-wrap2.png
  docs/team/huggenguggen.md
Labels: type.documentation, priority.High

#198 Bug fixes
  docs/UserGuide.md
  src/main/java/seedu/task/logic/commands/AddCommand.java
Labels: type.documentation, priority.High, type.Bug

#204 Ugdg corrections
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.High

#205 Update AlertActivityDiagram
  docs/diagrams/AlertActivityDiagram.puml
  docs/images/AlertActivityDiagram.png
Labels: type.documentation, priority.High, type.Bug

#206 Update UserGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/task/MainApp.java
  src/main/java/seedu/task/logic/commands/SortCommand.java
Labels: type.documentation, priority.High

#207 Preliminary coding style checks
  src/main/java/seedu/task/commons/core/index/Index.java
  src/main/java/seedu/task/commons/core/index/IndexList.java
  src/main/java/seedu/task/logic/commands/DeleteCommand.java
  src/main/java/seedu/task/logic/commands/PlanCommand.java
  src/main/java/seedu/task/logic/commands/ScheduleCommand.java
  src/main/java/seedu/task/logic/commands/StatsCommand.java
  src/main/java/seedu/task/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/task/model/ModelManager.java
  src/main/java/seedu/task/model/Planner.java
  src/main/java/seedu/task/model/TaskBook.java
  src/main/java/seedu/task/model/calendar/DailyPlan.java
  src/main/java/seedu/task/model/calendar/MonthlyPlan.java
  src/main/java/seedu/task/model/task/Deadline.java
  src/main/java/seedu/task/model/task/DeadlineList.java
  src/main/java/seedu/task/model/task/Effort.java
  src/main/java/seedu/task/model/task/EventList.java
  src/main/java/seedu/task/model/task/IsSameTaskPredicate.java
  src/main/java/seedu/task/model/task/SameEffortPredicate.java
  src/main/java/seedu/task/model/task/SimpleTaskList.java
  src/main/java/seedu/task/model/task/UniqueTaskList.java
  src/main/java/seedu/task/storage/StorageManager.java
Labels: type.CodeQuality

#211 Remove authorship for refactored code
  src/main/java/seedu/task/model/TaskBook.java
  src/main/java/seedu/task/model/task/UniqueTaskList.java
  src/main/java/seedu/task/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/task/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/task/storage/JsonSerializableTaskBook.java
  src/main/java/seedu/task/storage/JsonTaskBookStorage.java
  src/main/java/seedu/task/storage/Storage.java
  src/main/java/seedu/task/storage/StorageManager.java
  src/main/java/seedu/task/storage/TaskBookStorage.java
  src/main/java/seedu/task/ui/TaskListPanel.java
  src/test/java/seedu/task/commons/core/index/IndexTest.java
  src/test/java/seedu/task/logic/commands/ClearCommandTest.java
  src/test/java/seedu/task/model/TaskBookTest.java
  src/test/java/seedu/task/model/UserPrefsTest.java
  src/test/java/seedu/task/model/task/UniqueTaskListTest.java
  src/test/java/seedu/task/storage/JsonSerializableTaskBookTest.java
  src/test/java/seedu/task/storage/JsonTaskBookStorageTest.java
  src/test/java/seedu/task/storage/StorageManagerTest.java
  src/test/java/seedu/task/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/task/testutil/SimpleTaskBuilder.java
  src/test/java/seedu/task/testutil/TaskBookBuilder.java
  src/test/java/seedu/task/testutil/TestUtil.java
Labels: type.Chore

#212 Update AboutUs.md
  docs/AboutUs.md
Labels: type.documentation

#214 Update AboutUs.md
  docs/AboutUs.md
Labels: type.documentation

#219 Remove drop down section
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation

#221 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.documentation

#225 Update DG page break
  docs/DeveloperGuide.md
Labels: type.documentation
